[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
bluff = "DtPSuiwYsauE5PwRWZfYpu2ZeCxZ7iunSZhXvHFWWfx7"

[programs.devnet]
bluff = "DtPSuiwYsauE5PwRWZfYpu2ZeCxZ7iunSZhXvHFWWfx7"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
